name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
     - images/king.jpg
     - images/card.jpg


  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family : Pro
    fonts:
    - asset: fonts/Pro-Black.ttf